version: '3.7'

services:
  django-guni:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    networks:
      - ng_default
      
volumes:
  static:
    
networks:
  ng_default:
    external: true