# Generated by Django 4.2.3 on 2024-01-25 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agent', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('player_notes', models.TextField()),
                ('posts', models.ManyToManyField(related_name='agent_posts', to='firstapp.post')),
            ],
        ),
    ]
