# Generated by Django 4.2.3 on 2024-01-27 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_vacancies', to='firstapp.agent')),
                ('appliers', models.ManyToManyField(related_name='applied_vacancies', to='firstapp.player')),
            ],
        ),
    ]
