# Generated by Django 4.2.3 on 2023-09-15 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
