# Generated by Django 4.2.3 on 2024-01-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_vacancy_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='place',
            field=models.CharField(default='asdf', max_length=255),
            preserve_default=False,
        ),
    ]
