# Generated by Django 4.2.3 on 2024-02-21 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_vacancy_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
