# Generated by Django 4.2.3 on 2024-03-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='appliers',
        ),
    ]
