# Generated by Django 4.2.3 on 2023-09-30 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_like_comment_post_comments_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_posts', through='firstapp.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
