# Generated by Django 4.2.3 on 2023-09-30 17:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_alter_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_comments', through='firstapp.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
